//BEGIN GAMEBOARDOBJECT HOLDER
var gameBoardObject = [
  //ORDER OF CONTINENTS: NA, SA, EU, AF, OC, AS
  { "provincename":"NA1",
    "provinceindexnumber": 0,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA2", "AS7", "NA6"],
    "adjacentProvinceIndex":["1", "36", "5"],
    "continenton":"NA",
    getValues : function(){},

  },
  { "provincename":"NA2",
    "provinceindexnumber": 1,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA1", "NA3", "NA4", "NA6"],
    "adjacentProvinceIndex":["0", "2", "3", "5"],
    "continenton":"NA",
    getValues : function(){},

  },
  { "provincename":"NA3",
    "provinceindexnumber": 2,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA2", "NA4", "NA5", "EU1"],
    "adjacentProvinceIndex":["1", "3", "4", "13"],
    "continenton":"NA",
    getValues : function(){},

  },
  { "provincename":"NA4",
    "provinceindexnumber": 3,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA2", "NA3", "NA5", "NA6", "NA7", "NA8"],
    "adjacentProvinceIndex":["1", "2", "4", "5", "6", "7"],
    "continenton":"NA",
    getValues : function(){},

  },
  { "provincename":"NA5",
    "provinceindexnumber": 4,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA3", "NA4", "NA8"],
    "adjacentProvinceIndex":["2", "3", "7"],
    "continenton":"NA",
    getValues : function(){},

  },
  { "provincename":"NA6",
    "provinceindexnumber": 5,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA1", "NA2", "NA3", "NA4", "NA7"],
    "adjacentProvinceIndex":["0", "1", "2", "3", "6"],
    "continenton":"NA",
    getValues : function(){},

  },
  { "provincename":"NA7",
    "provinceindexnumber": 6,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA4", "NA6", "NA8", "NA9"],
    "adjacentProvinceIndex":["3", "5", "7", "8"],
    "continenton":"NA",
    getValues : function(){},

  },
  { "provincename":"NA8",
    "provinceindexnumber": 7,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA4", "NA5", "NA6", "NA7", "NA9"],
    "adjacentProvinceIndex":["3", "4", "5", "6", "8"],
    "continenton":"NA",
    getValues : function(){},

  },
  { "provincename":"NA9",
    "provinceindexnumber": 8,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA7", "NA8", "SA1"],
    "adjacentProvinceIndex":["6", "7", "9"],
    "continenton":"NA",
    getValues : function(){},

  },
  { "provincename":"SA1",
    "provinceindexnumber": 9,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA9", "SA2", "SA3"],
    "adjacentProvinceIndex":["8", "10", "11"],
    "continenton":"SA",
    getValues : function(){},

  },
  { "provincename":"SA2",
    "provinceindexnumber": 10,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["SA1", "SA3", "SA4", "AF1"],
    "adjacentProvinceIndex":["9", "11", "12", "20"],
    "continenton":"SA",
    getValues : function(){},

  },
  { "provincename":"SA3",
    "provinceindexnumber": 11,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["SA1", "SA2", "SA4"],
    "adjacentProvinceIndex":["9", "10", "12"],
    "continenton":"SA",
    getValues : function(){},

  },
  { "provincename":"SA4",
    "provinceindexnumber": 12,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["SA2", "SA3"],
    "adjacentProvinceIndex":["10", "11"],
    "continenton":"SA",
    getValues : function(){},

  },
  { "provincename":"EU1",
    "provinceindexnumber": 13,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA3", "EU2", "EU7"],
    "adjacentProvinceIndex":["2", "14", "19"],
    "continenton":"EU",
    getValues : function(){},

  },
  { "provincename":"EU2",
    "provinceindexnumber": 14,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["EU1", "EU3", "EU5", "EU7"],
    "adjacentProvinceIndex":["13", "15", "17", "19"],
    "continenton":"EU",
    getValues : function(){},

  },
  { "provincename":"EU3",
    "provinceindexnumber": 15,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["EU2", "EU4", "EU5", "AF1"],
    "adjacentProvinceIndex":["14", "16", "17", "20"],
    "continenton":"EU",
    getValues : function(){},

  },
  { "provincename":"EU4",
    "provinceindexnumber": 16,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["EU3", "EU5", "EU6", "AS1", "AF1", "AF2"],
    "adjacentProvinceIndex":["15", "17", "18", "30", "20", "21"],
    "continenton":"EU",
    getValues : function(){},

  },
  { "provincename":"EU5",
    "provinceindexnumber": 17,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["EU2", "EU3", "EU4", "EU6", "EU7"],
    "adjacentProvinceIndex":["14", "15", "16", "18", "19"],
    "continenton":"EU",
    getValues : function(){},

  },
  { "provincename":"EU6",
    "provinceindexnumber": 18,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["EU4", "EU5", "EU7", "AS1", "AS11", "AS12"],
    "adjacentProvinceIndex":["16", "17", "19", "30", "40", "41"],
    "continenton":"EU",
    getValues : function(){},

  },
  { "provincename":"EU7",
    "provinceindexnumber": 19,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["EU1", "EU2", "EU5", "EU6"],
    "adjacentProvinceIndex":["13", "14", "17", "18"],
    "continenton":"EU",
    getValues : function(){},

  },
  { "provincename":"AF1",
    "provinceindexnumber": 20,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["SA2", "EU3", "EU4", "AF2", "AF3", "AF4"],
    "adjacentProvinceIndex":["10", "15", "16", "21", "22", "23"],
    "continenton":"AF",
    getValues : function(){},

  },
  { "provincename":"AF2",
    "provinceindexnumber": 21,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AF1", "AF3", "EU4", "AS1"],
    "adjacentProvinceIndex":["20", "22", "16", "30"],
    "continenton":"AF",
    getValues : function(){},

  },
  { "provincename":"AF3",
    "provinceindexnumber": 22,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AF1", "AF2", "AF4", "AF5", "AF6", "AS1"],
    "adjacentProvinceIndex":["20", "21", "23", "24", "25", "30"],
    "continenton":"AF",
    getValues : function(){},

  },
  { "provincename":"AF4",
    "provinceindexnumber": 23,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AF1", "AF3", "AF5"],
    "adjacentProvinceIndex":["20", "22", "24"],
    "continenton":"AF",
    getValues : function(){},

  },
  { "provincename":"AF5",
    "provinceindexnumber": 24,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AF3", "AF4", "AF6"],
    "adjacentProvinceIndex":["22", "23", "25"],
    "continenton":"AF",
    getValues : function(){},

  },
  { "provincename":"AF6",
    "provinceindexnumber": 25,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AF3", "AF5"],
    "adjacentProvinceIndex":["22", "24"],
    "continenton":"AF",
    getValues : function(){},

  },
  { "provincename":"OC1",
    "provinceindexnumber": 26,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AS4", "OC2", "OC3"],
    "adjacentProvinceIndex":["33", "27", "28"],
    "continenton":"OC",
    getValues : function(){},

  },
  { "provincename":"OC2",
    "provinceindexnumber": 27,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["OC1", "OC3", "OC4"],
    "adjacentProvinceIndex":["26", "28", "29"],
    "continenton":"OC",
    getValues : function(){},

  },
  { "provincename":"OC3",
    "provinceindexnumber": 28,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["OC1", "OC2", "OC4"],
    "adjacentProvinceIndex":["26", "27", "29"],
    "continenton":"OC",
    getValues : function(){},

  },
  { "provincename":"OC4",
    "provinceindexnumber": 29,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["OC2", "OC3"],
    "adjacentProvinceIndex":["27", "28"],
    "continenton":"OC",
    getValues : function(){},

  },
  { "provincename":"AS1",
    "provinceindexnumber": 30,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["EU4", "EU6", "AF2", "AF3", "AS2", "AS3", "AS11"],
    "adjacentProvinceIndex":["16", "18", "21", "22", "31", "32", "40"],
    "continenton":"AS",
    getValues : function(){},

  },
  { "provincename":"AS2",
    "provinceindexnumber": 31,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AS1", "AS3", "AS4"],
    "adjacentProvinceIndex":["30", "32", "33"],
    "continenton":"AS",
    getValues : function(){},

  },
  { "provincename":"AS3",
    "provinceindexnumber": 32,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AS1", "AS2", "AS4", "AS5", "AS10", "AS12", "AS11"],
    "adjacentProvinceIndex":["30", "31", "33", "34", "39", "41", "40"],
    "continenton":"AS",
    getValues : function(){},

  },
  { "provincename":"AS4",
    "provinceindexnumber": 33,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AS2", "AS3", "OC1"],
    "adjacentProvinceIndex":["31", "32", "26"],
    "continenton":"AS",
    getValues : function(){},

  },
  { "provincename":"AS5",
    "provinceindexnumber": 34,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AS3", "AS6", "AS7", "AS8", "AS10"],
    "adjacentProvinceIndex":["32", "35", "36", "37", "39"],
    "continenton":"AS",
    getValues : function(){},

  },
  { "provincename":"AS6",
    "provinceindexnumber": 35,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AS5", "AS7"],
    "adjacentProvinceIndex":["34", "36"],
    "continenton":"AS",
    getValues : function(){},

  },
  { "provincename":"AS7",
    "provinceindexnumber": 36,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["NA1", "AS5", "AS6", "AS8", "AS9"],
    "adjacentProvinceIndex":["0", "34", "35", "37", "38"],
    "continenton":"AS",
    getValues : function(){},

  },
  { "provincename":"AS8",
    "provinceindexnumber": 37,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AS5", "AS7", "AS9", "AS10"],
    "adjacentProvinceIndex":["34", "36", "38", "39"],
    "continenton":"AS",
    getValues : function(){},

  },
  { "provincename":"AS9",
    "provinceindexnumber": 38,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AS7", "AS8", "AS10"],
    "adjacentProvinceIndex":["36", "37", "39"],
    "continenton":"AS",
    getValues : function(){},

  },
  { "provincename":"AS10",
    "provinceindexnumber": 39,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AS3", "AS5", "AS8", "AS9", "AS12"],
    "adjacentProvinceIndex":["32", "34", "37", "38", "41"],
    "continenton":"AS",
    getValues : function(){},

  },
  { "provincename":"AS11",
    "provinceindexnumber": 40,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AS1", "AS3", "AS12", "EU6"],
    "adjacentProvinceIndex":["30", "32", "41", "18"],
    "continenton":"AS",
    getValues : function(){},

  },
  { "provincename": "AS12",
    "provinceindexnumber": 41,
    "owner":"",
    "color":"black",
    "numberOfTroops":0,
    "valueToplayer2":0,
    "valueToplayer3":0,
    "valueToplayer4":0,
    "valueToplayer5":0,
    "valueToplayer6":0,
    "adjacentProvinces":["AS3", "AS10", "AS11", "EU6"],
    "adjacentProvinceIndex":["32", "39", "40", "18"],
    "continenton":"AS",
    getValues : function(){},

  },
];
//END GAMEBOARDOBJECT HOLDER
